version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=developmentDB
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  # Προσθήκη Adminer (ελαφρύ web interface)
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'    # Θα είναι προσβάσιμο στο http://localhost:8080
    depends_on:
      - db

volumes:
  db:
    driver: local